### ISSUE TITLE
localhost:5173 не відповідає

### ISSUE THREAD

**Issue by hrynevychroman** [joinposter/pos-platform-boilerplate#55]
На цьому кроці не зрозуміло що саме потрібно зробити, чи можна добавити screenshot-и аби легше було зрозуміти як саме налаштувати? Додав `applicationId` та `applicationSecret` проте також нічого не працює 😞 

> Вверху слева нажмите на вкладку prod</>, переключите ваше приложение в режим разработки. Введите адрес https://localhost:5173

<img width="729" alt="image" src="https://github.com/joinposter/pos-platform-boilerplate/assets/82209198/da539b09-f47a-4cf1-9c18-e0592e2d7ce3">

**Comment by DanielGots** [comment]
В Poster ви вказуєте адресу https://localhost:5173, а далі ми додаємо до цього посилання /bundle.js та завантажуємо скрипт в застосунок.

Перевірити чи нема проблем з підвантажуванням коду можна двома варіантами:

1. Відкрийте сторінку https://localhost:5173/bundle.js – повинен відобразитися код бандлу.
2. В Poster відкрийте консоль використовуючи Cmd (Ctrl) + Shift + U, вкладка Network. Вийдіть з вкладки prod</> та перевірте в Network чи завантажився скрипт з localhost
